name: summit

services:
  db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - summit_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: ./app/server
      dockerfile: Dockerfile

    env_file:
      - .env

    init: true

    ports:
      - "${SERVER_PORT}:3000"

    environment:
      SERVER_HOST: 0.0.0.0
      POSTGRES_HOST: db

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./app/server:/server
      - server_node_modules:/server/node_modules

    stop_grace_period: 10s

volumes:
  summit_postgres_data:
  server_node_modules: